In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'], inplace=True)

In [5]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [12]:
# Problem 1
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=weak
# Play or No Play?

# Solution
# P(Yes | Sunny,Hot,High,weak)=P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(weak | Yes) * P(Yes)
# P(No | Sunny,Hot,High,weak)=P(Sunny | No) * P(Hot | No) * P(High | No) * P(weak | No) * P(No)
# Compare and decide using the Maximum a posteriori rule

# Problem 2
# Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=weak
# Play or No Play?

# Training
# Lookup Table (Dictionary) # algorithm makes lookup table
# Testing

## LOOKUP TABLE:

In [8]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [9]:
py = 9/14
pn = 5/14

In [11]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [13]:
# outlook 

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [15]:
# temp

pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [16]:
PcoolNo = 1/5
PhotNo = 2/5
PmildNo = 2/5
PcoolYes = 3/9
PhotYes = 2/9
PmildYes = 4/9

In [18]:
# Humidity

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
PhighNo = 4/5
PnormalNo = 1/5
PhighYes = 3/9
PnormalYes = 6/9

In [21]:
# Outlook

pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [22]:
PstrongNo = 3/5
PweakNo = 2/5
PstrongYes = 3/9
PweakYes = 6/9

In [28]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=weak
# putting into formula

Pyes = py*Psy * PhotYes * PhighYes * PweakYes
print(Pyes)

Pno = pn * Psn * PhotNo * PhighNo * PweakNo
print(Pno)

0.007054673721340388
0.02742857142857143

In [29]:
Pyes>Pno

False

so,
No play!